
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.Label location;
	
	private global::Gtk.Entry host;
	
	private global::Gtk.ToggleButton connect;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.FileChooserButton modelFilePicker;
	
	private global::Gtk.Button getNext;
	
	private global::Gtk.Button hasNext;
	
	private global::Gtk.Button getData;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView log;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.location = new global::Gtk.Label ();
		this.location.Name = "location";
		this.location.Xalign = 0F;
		this.location.LabelProp = global::Mono.Unix.Catalog.GetString ("Loaction:");
		this.vbox4.Add (this.location);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.location]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.host = new global::Gtk.Entry ();
		this.host.CanFocus = true;
		this.host.Name = "host";
		this.host.IsEditable = true;
		this.host.InvisibleChar = '•';
		this.vbox4.Add (this.host);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.host]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.connect = new global::Gtk.ToggleButton ();
		this.connect.CanFocus = true;
		this.connect.Name = "connect";
		this.connect.UseUnderline = true;
		this.connect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
		this.vbox4.Add (this.connect);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.connect]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Model file");
		this.vbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label2]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.modelFilePicker = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.modelFilePicker.Sensitive = false;
		this.modelFilePicker.Name = "modelFilePicker";
		this.vbox4.Add (this.modelFilePicker);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.modelFilePicker]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.getNext = new global::Gtk.Button ();
		this.getNext.Sensitive = false;
		this.getNext.CanFocus = true;
		this.getNext.Name = "getNext";
		this.getNext.UseUnderline = true;
		this.getNext.Label = global::Mono.Unix.Catalog.GetString ("getNext");
		this.vbox4.Add (this.getNext);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.getNext]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hasNext = new global::Gtk.Button ();
		this.hasNext.Sensitive = false;
		this.hasNext.CanFocus = true;
		this.hasNext.Name = "hasNext";
		this.hasNext.UseUnderline = true;
		this.hasNext.Label = global::Mono.Unix.Catalog.GetString ("hasNext");
		this.vbox4.Add (this.hasNext);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hasNext]));
		w7.Position = 6;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.getData = new global::Gtk.Button ();
		this.getData.Sensitive = false;
		this.getData.CanFocus = true;
		this.getData.Name = "getData";
		this.getData.UseUnderline = true;
		this.getData.Label = global::Mono.Unix.Catalog.GetString ("getData");
		this.vbox4.Add (this.getData);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.getData]));
		w8.Position = 7;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox2.Add (this.vbox4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.log = new global::Gtk.TextView ();
		this.log.CanFocus = true;
		this.log.Name = "log";
		this.log.Editable = false;
		this.log.CursorVisible = false;
		this.log.AcceptsTab = false;
		this.GtkScrolledWindow.Add (this.log);
		this.hbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow]));
		w11.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 513;
		this.DefaultHeight = 290;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.connect.Toggled += new global::System.EventHandler (this.onConnectToggled);
		this.modelFilePicker.SelectionChanged += new global::System.EventHandler (this.OnModelSelectionChanged);
		this.getNext.Clicked += new global::System.EventHandler (this.onGetNext);
		this.hasNext.Clicked += new global::System.EventHandler (this.OnHasNext);
		this.getData.Clicked += new global::System.EventHandler (this.OnGetData);
	}
}
