package org.graphwalker;

import io.github.bonigarcia.wdm.FirefoxDriverManager;
import org.graphwalker.core.machine.ExecutionContext;
import org.graphwalker.java.annotation.AfterExecution;
import org.graphwalker.java.annotation.BeforeExecution;
import org.graphwalker.java.annotation.GraphWalker;
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * See: http://graphwalker.org/docs/maven_archetype for more details
 * <p>
 * Implements the GraphWalker model: src/main/resources/SmallTest.graphml
 * The SmallTest.graphml can be opened and edited using http://www.yworks.com/en/products/yfiles/yed/
 * <p>
 * For convienicene, a jpg image exists side-by-side in the same folder.
 * <p>
 * The @GraphWalker annotation, has the following meaning:
 * 1) value defines the generator of this test. Please read more
 * on the subject at: http://graphwalker.org/docs/path_generators_and_stop_conditions
 * 2) start defines the first element in the model to be executed. (Element is
 * either a vertex or an edge)
 * <p>
 * The interface SmallTest, that SomeSmallTest implements, is generated by
 * running: mvn graphwalker:generate-sources
 * also: mvn graphwalker:test
 */
@GraphWalker(value = "a_star(reached_vertex(v_ShoppingCart))", start = "e_StartBrowser")
public class ShoppingCartTest extends ExecutionContext implements ShoppingCart {

    private static final Logger logger = LoggerFactory.getLogger(ShoppingCartTest.class);
    WebDriver driver = null;
    WebDriverWait waiter = null;
    Integer numberOfAddedBooksByProgam = 0;

    @BeforeExecution
    public void setup() {
        FirefoxDriverManager.getInstance().setup();
    }

    @AfterExecution
    public void cleanup() {
        if (driver != null) {
            driver.quit();
        }
    }

    public void e_ClickBook() {
        waiter.until(ExpectedConditions.elementToBeClickable(By.linkText("Practical Model-Based Testing: A Tools Approach"))).click();
    }

    public void e_AddBookToCart() {
        waiter.until(ExpectedConditions.presenceOfElementLocated(By.id("add-to-cart-button")));
        waiter.until(ExpectedConditions.elementToBeClickable(By.id("add-to-cart-button"))).click();
        logger.debug("Number of added books by test: " + ++numberOfAddedBooksByProgam);
    }

    public void v_BookInformation() {
        waiter.until(ExpectedConditions.textMatches(By.tagName("h1"), Pattern.compile("Practical Model-Based Testing: A Tools Approach .*")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("mediaTabsGroup")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("navFooterVerticalColumn")));
    }

    public void v_OtherBoughtBooks() {
        waiter.until(ExpectedConditions.textMatches(By.tagName("h2"), Pattern.compile("Customers who bought .*")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("navFooterVerticalColumn")));
    }

    public void e_StartBrowser() {
        driver = new FirefoxDriver();
        Assert.assertNotNull(driver);
        waiter = new WebDriverWait(driver, 10);
    }

    public void v_SearchResult() {
        waiter.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Practical Model-Based Testing: A Tools Approach")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("resultsCol")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("navFooterVerticalColumn")));
    }

    public void v_ShoppingCart() {
        waiter.until(ExpectedConditions.titleContains("Amazon.com"));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.className("navFooterVerticalColumn")));
        Integer expected_num_of_books_by_graphwalker = ((Double) getAttribute("num_of_books")).intValue();

        // The number of books should be equal both in the model, and in this program
        Assert.assertEquals(expected_num_of_books_by_graphwalker, numberOfAddedBooksByProgam);


        if (expected_num_of_books_by_graphwalker == 0) {
            waiter.until(ExpectedConditions.textToBe(By.tagName("h1"), "Your Shopping Cart is empty."));
            return;
        }

        waiter.until(ExpectedConditions.presenceOfElementLocated(By.id("gutterCartViewForm")));
        String itemsInCart = driver.findElement(By.id("gutterCartViewForm")).getText();

        Pattern pattern = Pattern.compile("Subtotal \\(([0-9]+) items*\\):", Pattern.MULTILINE);
        Matcher matcher = pattern.matcher(itemsInCart);
        Integer actual_num_of_books_by_selenium = null;
        if (matcher.find()) {
            actual_num_of_books_by_selenium = Integer.valueOf(matcher.group(1));
        }

        // The number of books should be equal both in the model, and found by selenium in the system under test
        Assert.assertEquals(expected_num_of_books_by_graphwalker, actual_num_of_books_by_selenium);
    }

    public void e_EnterBaseURL() {
        driver.get("http://www.amazon.com");
    }

    public void v_BaseURL() {
        waiter.until(ExpectedConditions.titleContains("Amazon.com: Online Shopping "));
    }

    public void v_BrowserStarted() {
        Assert.assertNotNull(driver);
    }

    public void e_SearchBook() {
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("twotabsearchtextbox")));
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("twotabsearchtextbox"))).clear();
        waiter.until(ExpectedConditions.visibilityOfElementLocated(By.id("twotabsearchtextbox"))).sendKeys("Model-based testing" + Keys.ENTER);
    }

    public void e_ShoppingCart() {
        waiter.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\"nav-cart\"]"))).click();
    }
}
